
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (1,'Algeria',1,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (2,'Angola',1,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (3,'Benin',1,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (4,'Botswana',1,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (5,'Burkina Faso',1,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (6,'Burundi',1,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (7,'Cameroon',1,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (8,'Cape Verde Islands',1,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (9,'Central African Republic',1,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (10,'Chad',1,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (11,'Comoros',1,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (12,'Congo DR',1,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (13,'Congo',1,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (14,'C?te d\'Ivoire',1,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (15,'Djibouti',1,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (16,'Egypt',1,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (17,'Equatorial Guinea',1,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (18,'Eritrea',1,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (19,'Ethiopia',1,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (20,'Gabon',1,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (21,'Gambia',1,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (22,'Ghana',1,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (23,'Guinea-Bissau',1,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (24,'Guinea',1,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (25,'Kenya',1,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (26,'Lesotho',1,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (27,'Liberia',1,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (28,'Libya',1,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (29,'Madagascar',1,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (30,'Malawi',1,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (31,'Mali',1,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (32,'Mauritania',1,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (33,'Mauritius',1,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (34,'Morocco',1,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (35,'Mozambique',1,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (36,'Namibia',1,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (37,'Nigeria',1,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (38,'Niger',1,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (39,'Rwanda',1,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (40,'Sao Tome e Principe ',1,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (41,'Senegal',1,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (42,'Seychelles',1,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (43,'Sierra Leone',1,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (44,'Somalia',1,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (45,'South Africa',1,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (46,'South Sudan',1,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (47,'Sudan',1,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (48,'Swaziland',1,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (49,'Tanzania',1,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (50,'Togo',1,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (51,'Tunisia',1,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (52,'Uganda',1,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (53,'Zambia',1,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (54,'Afghanistan',2,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (55,'Australia',2,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (56,'Bahrain',2,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (57,'Bangladesh',2,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (58,'Bhutan',2,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (59,'Brunei Darussalam',2,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (60,'Cambodia',2,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (61,'China PR',2,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (62,'Chinese Taipei',2,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (63,'Guam',2,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (64,'Hong Kong',2,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (65,'India',2,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (66,'Iran',2,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (67,'Iraq',2,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (68,'Japan',2,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (69,'Jordan',2,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (70,'Korea DPR',2,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (71,'Korea Republic',2,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (72,'Kuwait',2,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (73,'Kyrgyzstan',2,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (74,'Laos',2,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (75,'Lebanon',2,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (76,'Macau',2,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (77,'Malaysia',2,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (78,'Maldives',2,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (79,'Mongolia',2,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (80,'Myanmar',2,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (81,'Nepal',2,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (82,'Oman',2,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (83,'Pakistan',2,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (84,'Palestine',2,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (85,'Philippines',2,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (86,'Qatar',2,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (87,'Saudi Arabia',2,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (88,'Singapore',2,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (89,'Sri Lanka',2,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (90,'Syria',2,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (91,'Tajikistan',2,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (92,'Thailand',2,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (93,'Timor-Leste',2,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (94,'Turkmenistan',2,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (95,'United Arab Emirates',2,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (96,'Uzbekistan',2,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (97,'Vietnam',2,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (98,'Yemen',2,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (99,'Russia',3,'1');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (100,'Albania',3,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (101,'Andorra',3,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (102,'Armenia',3,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (103,'Austria',3,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (104,'Azerbaijan',3,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (105,'Belarus',3,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (106,'Belgium',3,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (107,'Bosnia and Herzegovina',3,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (108,'Bulgaria',3,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (109,'Croatia',3,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (110,'Cyprus',3,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (111,'Czech Republic',3,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (112,'Denmark',3,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (113,'England',3,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (114,'Estonia',3,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (115,'Faroe Islands',3,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (116,'Finland',3,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (117,'France',3,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (118,'FYR Macedonia',3,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (119,'Georgia',3,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (120,'Germany',3,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (121,'Greece',3,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (122,'Hungary',3,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (123,'Iceland',3,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (124,'Israel',3,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (125,'Italy',3,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (126,'Kazakhstan',3,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (127,'Latvia',3,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (128,'Liechtenstein',3,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (129,'Lithuania',3,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (130,'Luxembourg',3,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (131,'Malta',3,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (132,'Moldova',3,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (133,'Montenegro',3,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (134,'Netherlands',3,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (135,'Northern Ireland',3,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (136,'Norway',3,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (137,'Poland',3,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (138,'Portugal',3,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (139,'Republic of Ireland',3,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (140,'Romania',3,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (141,'San Marino',3,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (142,'Scotland',3,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (143,'Serbia',3,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (144,'Slovakia',3,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (145,'Slovenia',3,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (146,'Spain',3,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (147,'Sweden',3,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (148,'Switzerland',3,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (149,'Turkey',3,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (150,'Ukraine',3,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (151,'Wales',3,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (152,'Anguilla',4,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (153,'Antigua and Barbuda',4,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (154,'Aruba',4,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (155,'Bahamas',4,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (156,'Barbados',4,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (157,'Belize',4,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (158,'Bermuda',4,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (159,'British Virgin Islands',4,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (160,'Canada',4,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (161,'Cayman Islands',4,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (162,'Costa Rica',4,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (163,'Cuba',4,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (164,'Curacao',4,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (165,'Dominica',4,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (166,'Dominican Republic',4,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (167,'El Salvador',4,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (168,'Grenada',4,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (169,'Guatemala',4,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (170,'Guyana',4,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (171,'Haiti',4,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (172,'Honduras',4,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (173,'Jamaica',4,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (174,'Mexico',4,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (175,'Montserrat',4,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (176,'Nicaragua',4,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (177,'Panama',4,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (178,'Puerto Rico',4,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (179,'St. Kitts and Nevis',4,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (180,'St. Lucia',4,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (181,'St. Vincent / Grenadines',4,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (182,'Suriname',4,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (183,'Trinidad and Tobago',4,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (184,'Turks and Caicos Islands',4,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (185,'US Virgin Islands',4,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (186,'USA',4,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (187,'American Samoa',5,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (188,'Cook Islands',5,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (189,'Fiji',5,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (190,'New Caledonia',5,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (191,'New Zealand',5,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (192,'Papua New Guinea',5,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (193,'Samoa',5,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (194,'Solomon Islands',5,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (195,'Tahiti',5,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (196,'Tonga',5,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (197,'Vanuatu',5,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (198,'Argentina',6,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (199,'Bolivia',6,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (200,'Brazil',6,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (201,'Chile',6,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (202,'Colombia',6,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (203,'Ecuador',6,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (204,'Paraguay',6,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (205,'Peru',6,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (206,'Uruguay',6,'0');
INSERT INTO `country` (`id`,`name`,`zone_id`,`qualified`) VALUES (207,'Venezuela',6,'0');

INSERT INTO `zone` (`id`,`name`,`description`) VALUES (ID,'NAME','DESCRIPTION');
INSERT INTO `zone` (`id`,`name`,`description`) VALUES (1,'Africa','The Confederation of African Football\'s Preliminary Competition offers five berths at the 2018 FIFA World Cup Russia&trade;.');
INSERT INTO `zone` (`id`,`name`,`description`) VALUES (2,'Asia','The Confederation of Asian Football\'s Preliminary Competition offers four and a half berths at the 2018 FIFA World Cup Russia&trade;.');
INSERT INTO `zone` (`id`,`name`,`description`) VALUES (3,'Europe','Europe’s Preliminary Competition offers the highest number of berths at the 2018 FIFA World Cup Russia&trade;: thirteen in total.');
INSERT INTO `zone` (`id`,`name`,`description`) VALUES (4,'North, Central America and Caribbean','The North, Central America and Caribbean’s Preliminary Competition offers three and a half berths at the 2018 FIFA World Cup Russia&trade;.');
INSERT INTO `zone` (`id`,`name`,`description`) VALUES (5,'Oceania','The Oceania Football Confederation’s Preliminary Competition offers half a berth at the 2018 FIFA World Cup Russia&trade;.');
INSERT INTO `zone` (`id`,`name`,`description`) VALUES (6,'South America','South America’s Preliminary Competition offers four and a half berths at the 2018 FIFA World Cup Russia&trade;.');